-- Create the normalized per-view table.
-- Each row is a single view; a dataset that exposes multiple views (e.g. map + gallery)
-- becomes multiple rows that share the same primary_dataset.
CREATE TABLE views (
  view_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  view_name text,
  view_type text NOT NULL,
  primary_dataset text NOT NULL,
  secondary_dataset text,
  view_config text NOT NULL
);
--> statement-breakpoint
-- Backfill from the legacy view_config table.
-- Each legacy row holds a comma-separated VIEWS list inside its views_config JSON;
-- we expand that list into one row per view type. VIEWS is parsed exactly once, here.
INSERT INTO views (view_name, view_type, primary_dataset, secondary_dataset, view_config)
SELECT DISTINCT ON (legacy.table_name, btrim(view_token))
  COALESCE(NULLIF(btrim(legacy.views_config::jsonb ->> 'DATASET_TABLE'), ''), legacy.table_name),
  btrim(view_token),
  legacy.table_name,
  CASE WHEN btrim(view_token) = 'alerts'
       THEN NULLIF(btrim(legacy.views_config::jsonb ->> 'MAPEO_TABLE'), '')
       ELSE NULL END,
  (legacy.views_config::jsonb - 'VIEWS')::text
FROM view_config legacy
CROSS JOIN LATERAL unnest(string_to_array(legacy.views_config::jsonb ->> 'VIEWS', ',')) AS view_token
WHERE btrim(view_token) IN ('alerts', 'map', 'gallery');
--> statement-breakpoint
-- Drop the legacy table; its data has been transformed into `views`.
DROP TABLE view_config;
